PROMPT === Ajustes e carga da origem OLTP a partir do schema PF1788 ===
PROMPT === Execute este arquivo com F5 (Run Script) ===

ALTER TABLE CP_CIDADE MODIFY NOM_CIDADE VARCHAR2(50);
ALTER TABLE CP_PEDIDO ADD STATUS VARCHAR2(30);

DELETE FROM CP_ITEM_PEDIDO;
DELETE FROM CP_HISTORICO_PEDIDO;
DELETE FROM CP_PEDIDO;
DELETE FROM CP_CLIENTE_VENDEDOR;
DELETE FROM CP_MOVIMENTO_ESTOQUE;
DELETE FROM CP_ESTOQUE_PRODUTO;
DELETE FROM CP_ESTOQUE;
DELETE FROM CP_TIPO_MOVIMENTO_ESTOQUE;
DELETE FROM CP_PRODUTO_COMPOSTO;
DELETE FROM CP_PRODUTO;
DELETE FROM CP_VENDEDOR;
DELETE FROM CP_USUARIO;
DELETE FROM CP_ENDERECO_CLIENTE;
DELETE FROM CP_CLIENTE;
DELETE FROM CP_TIPO_ENDERECO;
DELETE FROM CP_CIDADE;
DELETE FROM CP_ESTADO;
DELETE FROM CP_PAIS;
COMMIT;

INSERT INTO CP_PAIS SELECT * FROM PF1788.PAIS;
COMMIT;

INSERT INTO CP_ESTADO SELECT * FROM PF1788.ESTADO;
COMMIT;

INSERT INTO CP_CIDADE SELECT * FROM PF1788.CIDADE;
COMMIT;

INSERT INTO CP_TIPO_ENDERECO SELECT * FROM PF1788.TIPO_ENDERECO;
COMMIT;

INSERT INTO CP_CLIENTE SELECT * FROM PF1788.CLIENTE;
COMMIT;

INSERT INTO CP_ENDERECO_CLIENTE SELECT * FROM PF1788.ENDERECO_CLIENTE;
COMMIT;

INSERT INTO CP_USUARIO SELECT * FROM PF1788.USUARIO;
COMMIT;

INSERT INTO CP_VENDEDOR SELECT * FROM PF1788.VENDEDOR;
COMMIT;

INSERT INTO CP_PRODUTO SELECT * FROM PF1788.PRODUTO;
COMMIT;

INSERT INTO CP_PRODUTO_COMPOSTO SELECT * FROM PF1788.PRODUTO_COMPOSTO;
COMMIT;

INSERT INTO CP_TIPO_MOVIMENTO_ESTOQUE SELECT * FROM PF1788.TIPO_MOVIMENTO_ESTOQUE;
COMMIT;

INSERT INTO CP_ESTOQUE SELECT * FROM PF1788.ESTOQUE;
COMMIT;

INSERT INTO CP_ESTOQUE_PRODUTO SELECT * FROM PF1788.ESTOQUE_PRODUTO;
COMMIT;

INSERT INTO CP_MOVIMENTO_ESTOQUE SELECT * FROM PF1788.MOVIMENTO_ESTOQUE;
COMMIT;

INSERT INTO CP_CLIENTE_VENDEDOR SELECT * FROM PF1788.CLIENTE_VENDEDOR;
COMMIT;

INSERT INTO CP_PEDIDO SELECT * FROM PF1788.PEDIDO;
COMMIT;

INSERT INTO CP_HISTORICO_PEDIDO SELECT * FROM PF1788.HISTORICO_PEDIDO;
COMMIT;

INSERT INTO CP_ITEM_PEDIDO SELECT * FROM PF1788.ITEM_PEDIDO;
COMMIT;

PROMPT === Contagens rápidas da origem ===
SELECT 'CP_PRODUTO' AS TABELA, COUNT(*) AS QTD FROM CP_PRODUTO
UNION ALL SELECT 'CP_ESTOQUE', COUNT(*) FROM CP_ESTOQUE
UNION ALL SELECT 'CP_TIPO_MOVIMENTO_ESTOQUE', COUNT(*) FROM CP_TIPO_MOVIMENTO_ESTOQUE
UNION ALL SELECT 'CP_ESTOQUE_PRODUTO', COUNT(*) FROM CP_ESTOQUE_PRODUTO
UNION ALL SELECT 'CP_MOVIMENTO_ESTOQUE', COUNT(*) FROM CP_MOVIMENTO_ESTOQUE;
