-- 02_staging.sql
-- Recria a staging consolidando pedido, item, cliente, vendedor, produto e local.
-- Ajuste importante: quando o pedido nao possuir SEQ_ENDERECO_CLIENTE valido,
-- o script tenta usar um endereco ativo do cliente como fallback.

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE STG_VENDA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE STG_VENDA AS
SELECT
    p.COD_PEDIDO,
    p.DAT_PEDIDO,
    p.DAT_CANCELAMENTO,
    p.COD_CLIENTE,
    c.NOM_CLIENTE,
    c.DES_RAZAO_SOCIAL,
    c.TIP_PESSOA,
    c.STA_ATIVO AS STA_CLIENTE,
    p.COD_VENDEDOR,
    v.NOM_VENDEDOR,
    v.STA_ATIVO AS STA_VENDEDOR,
    ip.COD_ITEM_PEDIDO,
    ip.COD_PRODUTO,
    pr.NOM_PRODUTO,
    pr.COD_BARRA,
    pr.STA_ATIVO AS STA_PRODUTO,
    ip.QTD_ITEM,
    ip.VAL_UNITARIO_ITEM,
    ip.VAL_DESCONTO_ITEM,
    (ip.QTD_ITEM * ip.VAL_UNITARIO_ITEM) - NVL(ip.VAL_DESCONTO_ITEM, 0) AS VAL_TOTAL_ITEM,
    NVL(ec_pedido.SEQ_ENDERECO_CLIENTE, ec_cliente.SEQ_ENDERECO_CLIENTE) AS SEQ_ENDERECO_CLIENTE,
    NVL(ec_pedido.COD_CIDADE, ec_cliente.COD_CIDADE) AS COD_CIDADE,
    ci.NOM_CIDADE,
    e.COD_ESTADO,
    e.NOM_ESTADO,
    pa.COD_PAIS,
    pa.NOM_PAIS
FROM CP_PEDIDO p
JOIN CP_ITEM_PEDIDO ip
    ON p.COD_PEDIDO = ip.COD_PEDIDO
LEFT JOIN CP_CLIENTE c
    ON p.COD_CLIENTE = c.COD_CLIENTE
LEFT JOIN CP_VENDEDOR v
    ON p.COD_VENDEDOR = v.COD_VENDEDOR
LEFT JOIN CP_PRODUTO pr
    ON ip.COD_PRODUTO = pr.COD_PRODUTO
LEFT JOIN CP_ENDERECO_CLIENTE ec_pedido
    ON p.SEQ_ENDERECO_CLIENTE = ec_pedido.SEQ_ENDERECO_CLIENTE
LEFT JOIN (
    SELECT COD_CLIENTE, MIN(SEQ_ENDERECO_CLIENTE) AS SEQ_ENDERECO_CLIENTE
    FROM CP_ENDERECO_CLIENTE
    WHERE STA_ATIVO = 'S'
    GROUP BY COD_CLIENTE
) ec_ativo
    ON p.COD_CLIENTE = ec_ativo.COD_CLIENTE
LEFT JOIN CP_ENDERECO_CLIENTE ec_cliente
    ON ec_ativo.SEQ_ENDERECO_CLIENTE = ec_cliente.SEQ_ENDERECO_CLIENTE
LEFT JOIN CP_CIDADE ci
    ON ci.COD_CIDADE = NVL(ec_pedido.COD_CIDADE, ec_cliente.COD_CIDADE)
LEFT JOIN CP_ESTADO e
    ON ci.COD_ESTADO = e.COD_ESTADO
LEFT JOIN CP_PAIS pa
    ON e.COD_PAIS = pa.COD_PAIS;
