-- 02_staging.sql
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE STG_VENDA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE STG_VENDA AS
SELECT
    p.COD_PEDIDO,
    p.DAT_PEDIDO,
    p.DAT_CANCELAMENTO,
    p.COD_CLIENTE,
    c.NOM_CLIENTE,
    c.DES_RAZAO_SOCIAL,
    c.TIP_PESSOA,
    c.STA_ATIVO AS STA_CLIENTE,
    p.COD_VENDEDOR,
    v.NOM_VENDEDOR,
    v.STA_ATIVO AS STA_VENDEDOR,
    ip.COD_ITEM_PEDIDO,
    ip.COD_PRODUTO,
    pr.NOM_PRODUTO,
    pr.COD_BARRA,
    pr.STA_ATIVO AS STA_PRODUTO,
    ip.QTD_ITEM,
    ip.VAL_UNITARIO_ITEM,
    ip.VAL_DESCONTO_ITEM,
    (ip.QTD_ITEM * ip.VAL_UNITARIO_ITEM) - NVL(ip.VAL_DESCONTO_ITEM, 0) AS VAL_TOTAL_ITEM,
    ec.SEQ_ENDERECO_CLIENTE,
    ci.COD_CIDADE,
    ci.NOM_CIDADE,
    e.COD_ESTADO,
    e.NOM_ESTADO,
    pa.COD_PAIS,
    pa.NOM_PAIS
FROM CP_PEDIDO p
JOIN CP_ITEM_PEDIDO ip ON p.COD_PEDIDO = ip.COD_PEDIDO
LEFT JOIN CP_CLIENTE c ON p.COD_CLIENTE = c.COD_CLIENTE
LEFT JOIN CP_VENDEDOR v ON p.COD_VENDEDOR = v.COD_VENDEDOR
LEFT JOIN CP_PRODUTO pr ON ip.COD_PRODUTO = pr.COD_PRODUTO
LEFT JOIN CP_ENDERECO_CLIENTE ec ON p.SEQ_ENDERECO_CLIENTE = ec.SEQ_ENDERECO_CLIENTE
LEFT JOIN CP_CIDADE ci ON ec.COD_CIDADE = ci.COD_CIDADE
LEFT JOIN CP_ESTADO e ON ci.COD_ESTADO = e.COD_ESTADO
LEFT JOIN CP_PAIS pa ON e.COD_PAIS = pa.COD_PAIS;
