-- 04_carga_dimensoes.sql
INSERT INTO DIM_TEMPO (DATA_COMPLETA, DIA, MES, ANO, NOME_MES)
SELECT DISTINCT
    TRUNC(DAT_PEDIDO),
    EXTRACT(DAY FROM DAT_PEDIDO),
    EXTRACT(MONTH FROM DAT_PEDIDO),
    EXTRACT(YEAR FROM DAT_PEDIDO),
    TRIM(TO_CHAR(DAT_PEDIDO, 'MONTH', 'NLS_DATE_LANGUAGE=PORTUGUESE'))
FROM STG_VENDA
WHERE DAT_PEDIDO IS NOT NULL;
COMMIT;

INSERT INTO DIM_CLIENTE (COD_CLIENTE, NOM_CLIENTE, DES_RAZAO_SOCIAL, TIP_PESSOA, STA_ATIVO)
SELECT DISTINCT COD_CLIENTE, NOM_CLIENTE, DES_RAZAO_SOCIAL, TIP_PESSOA, STA_CLIENTE
FROM STG_VENDA
WHERE COD_CLIENTE IS NOT NULL;
COMMIT;

INSERT INTO DIM_VENDEDOR (COD_VENDEDOR, NOM_VENDEDOR, STA_ATIVO)
SELECT DISTINCT COD_VENDEDOR, NOM_VENDEDOR, STA_VENDEDOR
FROM STG_VENDA
WHERE COD_VENDEDOR IS NOT NULL;
COMMIT;

INSERT INTO DIM_PRODUTO (COD_PRODUTO, NOM_PRODUTO, COD_BARRA, STA_ATIVO)
SELECT DISTINCT COD_PRODUTO, NOM_PRODUTO, COD_BARRA, STA_PRODUTO
FROM STG_VENDA
WHERE COD_PRODUTO IS NOT NULL;
COMMIT;

INSERT INTO DIM_LOCAL (COD_CIDADE, NOM_CIDADE, COD_ESTADO, NOM_ESTADO, COD_PAIS, NOM_PAIS)
SELECT DISTINCT COD_CIDADE, NOM_CIDADE, COD_ESTADO, NOM_ESTADO, COD_PAIS, NOM_PAIS
FROM STG_VENDA
WHERE COD_CIDADE IS NOT NULL;
COMMIT;
