PROMPT === Procedure SP_CARGA_DIM_TEMPO ===

CREATE OR REPLACE PROCEDURE SP_CARGA_DIM_TEMPO IS
    V_QTD NUMBER := 0;
BEGIN
    MERGE INTO DIM_TEMPO D
    USING (
        SELECT DATE '1900-01-01' AS DAT_COMPLETA FROM DUAL
        UNION
        SELECT DISTINCT NVL(TRUNC(DAT_MOVIMENTO_ESTOQUE), DATE '1900-01-01') AS DAT_COMPLETA
        FROM CP_MOVIMENTO_ESTOQUE
    ) S
       ON (D.DAT_COMPLETA = S.DAT_COMPLETA)
    WHEN MATCHED THEN UPDATE SET
        D.NUM_ANO        = EXTRACT(YEAR FROM S.DAT_COMPLETA),
        D.NUM_MES        = EXTRACT(MONTH FROM S.DAT_COMPLETA),
        D.NOM_MES        = TRIM(TO_CHAR(S.DAT_COMPLETA, 'MONTH', 'NLS_DATE_LANGUAGE=PORTUGUESE')),
        D.NUM_TRIMESTRE  = TO_NUMBER(TO_CHAR(S.DAT_COMPLETA, 'Q')),
        D.NUM_DIA_SEMANA = TO_NUMBER(TO_CHAR(S.DAT_COMPLETA, 'D')),
        D.NOM_DIA_SEMANA = TRIM(TO_CHAR(S.DAT_COMPLETA, 'DAY', 'NLS_DATE_LANGUAGE=PORTUGUESE'))
    WHEN NOT MATCHED THEN INSERT (
        DAT_COMPLETA,
        NUM_ANO,
        NUM_MES,
        NOM_MES,
        NUM_TRIMESTRE,
        NUM_DIA_SEMANA,
        NOM_DIA_SEMANA
    ) VALUES (
        S.DAT_COMPLETA,
        EXTRACT(YEAR FROM S.DAT_COMPLETA),
        EXTRACT(MONTH FROM S.DAT_COMPLETA),
        TRIM(TO_CHAR(S.DAT_COMPLETA, 'MONTH', 'NLS_DATE_LANGUAGE=PORTUGUESE')),
        TO_NUMBER(TO_CHAR(S.DAT_COMPLETA, 'Q')),
        TO_NUMBER(TO_CHAR(S.DAT_COMPLETA, 'D')),
        TRIM(TO_CHAR(S.DAT_COMPLETA, 'DAY', 'NLS_DATE_LANGUAGE=PORTUGUESE'))
    );

    V_QTD := SQL%ROWCOUNT;
    COMMIT;

    SP_REGISTRA_LOG_ETL('SP_CARGA_DIM_TEMPO', V_QTD, 'SUCESSO', 'Carga concluída com MERGE.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        SP_REGISTRA_LOG_ETL('SP_CARGA_DIM_TEMPO', 0, 'ERRO', SQLERRM);
        RAISE;
END;
/

PROMPT === Executando SP_CARGA_DIM_TEMPO ===
BEGIN
    SP_CARGA_DIM_TEMPO;
END;
/
