-- 06_carga_fato.sql
-- Script idempotente: limpa a fato antes de recarregar.

TRUNCATE TABLE FATO_VENDA;

INSERT INTO FATO_VENDA (
    COD_PEDIDO,
    COD_ITEM_PEDIDO,
    SK_TEMPO,
    SK_CLIENTE,
    SK_VENDEDOR,
    SK_PRODUTO,
    SK_LOCAL,
    QTD_ITEM,
    VAL_UNITARIO,
    VAL_DESCONTO,
    VAL_TOTAL_ITEM
)
SELECT
    s.COD_PEDIDO,
    s.COD_ITEM_PEDIDO,
    dt.SK_TEMPO,
    dc.SK_CLIENTE,
    dv.SK_VENDEDOR,
    dp.SK_PRODUTO,
    dl.SK_LOCAL,
    s.QTD_ITEM,
    s.VAL_UNITARIO_ITEM,
    NVL(s.VAL_DESCONTO_ITEM, 0),
    s.VAL_TOTAL_ITEM
FROM STG_VENDA s
JOIN DIM_TEMPO dt
    ON TRUNC(dt.DATA_COMPLETA) = TRUNC(s.DAT_PEDIDO)
JOIN DIM_CLIENTE dc
    ON dc.COD_CLIENTE = s.COD_CLIENTE
JOIN DIM_VENDEDOR dv
    ON dv.COD_VENDEDOR = s.COD_VENDEDOR
JOIN DIM_PRODUTO dp
    ON dp.COD_PRODUTO = s.COD_PRODUTO
JOIN DIM_LOCAL dl
    ON dl.COD_CIDADE = s.COD_CIDADE
   AND NVL(dl.COD_ESTADO, 'X') = NVL(s.COD_ESTADO, 'X')
   AND NVL(dl.COD_PAIS, -1) = NVL(s.COD_PAIS, -1);
COMMIT;
