PROMPT === Procedure SP_CARGA_DIM_TIPO_MOVIMENTO ===

CREATE OR REPLACE PROCEDURE SP_CARGA_DIM_TIPO_MOVIMENTO IS
    V_QTD NUMBER := 0;
BEGIN
    MERGE INTO DIM_TIPO_MOVIMENTO D
    USING (
        SELECT
            -1 AS COD_TIPO_MOVIMENTO_ESTOQUE,
            'NAO INFORMADO' AS DES_TIPO_MOVIMENTO_ESTOQUE,
            'N' AS STA_SAIDA_ENTRADA
        FROM DUAL
        UNION ALL
        SELECT
            COD_TIPO_MOVIMENTO_ESTOQUE,
            DES_TIPO_MOVIMENTO_ESTOQUE,
            STA_SAIDA_ENTRADA
        FROM CP_TIPO_MOVIMENTO_ESTOQUE
    ) S
       ON (D.COD_TIPO_MOVIMENTO_ESTOQUE = S.COD_TIPO_MOVIMENTO_ESTOQUE)
    WHEN MATCHED THEN UPDATE SET
        D.DES_TIPO_MOVIMENTO_ESTOQUE = S.DES_TIPO_MOVIMENTO_ESTOQUE,
        D.STA_SAIDA_ENTRADA          = S.STA_SAIDA_ENTRADA
    WHEN NOT MATCHED THEN INSERT (
        COD_TIPO_MOVIMENTO_ESTOQUE,
        DES_TIPO_MOVIMENTO_ESTOQUE,
        STA_SAIDA_ENTRADA
    ) VALUES (
        S.COD_TIPO_MOVIMENTO_ESTOQUE,
        S.DES_TIPO_MOVIMENTO_ESTOQUE,
        S.STA_SAIDA_ENTRADA
    );

    V_QTD := SQL%ROWCOUNT;
    COMMIT;

    SP_REGISTRA_LOG_ETL('SP_CARGA_DIM_TIPO_MOVIMENTO', V_QTD, 'SUCESSO', 'Carga concluída com MERGE.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        SP_REGISTRA_LOG_ETL('SP_CARGA_DIM_TIPO_MOVIMENTO', 0, 'ERRO', SQLERRM);
        RAISE;
END;
/

PROMPT === Executando SP_CARGA_DIM_TIPO_MOVIMENTO ===
BEGIN
    SP_CARGA_DIM_TIPO_MOVIMENTO;
END;
/
