-- 07_consultas_analiticas.sql
SELECT dl.NOM_ESTADO, SUM(fv.VAL_TOTAL_ITEM) AS TOTAL_VENDAS
FROM FATO_VENDA fv
JOIN DIM_LOCAL dl ON fv.SK_LOCAL = dl.SK_LOCAL
GROUP BY dl.NOM_ESTADO
ORDER BY TOTAL_VENDAS DESC;

SELECT dt.ANO, SUM(fv.VAL_TOTAL_ITEM) AS TOTAL_VENDAS
FROM FATO_VENDA fv
JOIN DIM_TEMPO dt ON fv.SK_TEMPO = dt.SK_TEMPO
GROUP BY dt.ANO
ORDER BY dt.ANO;

SELECT dt.ANO, dt.MES, dt.NOME_MES, SUM(fv.VAL_TOTAL_ITEM) AS TOTAL_VENDAS
FROM FATO_VENDA fv
JOIN DIM_TEMPO dt ON fv.SK_TEMPO = dt.SK_TEMPO
GROUP BY dt.ANO, dt.MES, dt.NOME_MES
ORDER BY dt.ANO, dt.MES;

SELECT dv.NOM_VENDEDOR, SUM(fv.VAL_TOTAL_ITEM) AS TOTAL_VENDAS
FROM FATO_VENDA fv
JOIN DIM_VENDEDOR dv ON fv.SK_VENDEDOR = dv.SK_VENDEDOR
GROUP BY dv.NOM_VENDEDOR
ORDER BY TOTAL_VENDAS DESC;

SELECT dc.NOM_CLIENTE, SUM(fv.VAL_TOTAL_ITEM) AS TOTAL_VENDAS
FROM FATO_VENDA fv
JOIN DIM_CLIENTE dc ON fv.SK_CLIENTE = dc.SK_CLIENTE
GROUP BY dc.NOM_CLIENTE
ORDER BY TOTAL_VENDAS DESC;

SELECT dp.NOM_PRODUTO, SUM(fv.VAL_TOTAL_ITEM) AS RECEITA_TOTAL
FROM FATO_VENDA fv
JOIN DIM_PRODUTO dp ON fv.SK_PRODUTO = dp.SK_PRODUTO
GROUP BY dp.NOM_PRODUTO
ORDER BY RECEITA_TOTAL DESC
FETCH FIRST 1 ROWS ONLY;

SELECT dc.TIP_PESSOA, dl.NOM_ESTADO, COUNT(*) AS QTDE_ITENS, SUM(fv.VAL_TOTAL_ITEM) AS TOTAL_GASTO
FROM FATO_VENDA fv
JOIN DIM_CLIENTE dc ON fv.SK_CLIENTE = dc.SK_CLIENTE
JOIN DIM_LOCAL dl ON fv.SK_LOCAL = dl.SK_LOCAL
GROUP BY dc.TIP_PESSOA, dl.NOM_ESTADO
ORDER BY TOTAL_GASTO DESC;
