PROMPT === Procedure SP_CARGA_DIM_ESTOQUE ===

CREATE OR REPLACE PROCEDURE SP_CARGA_DIM_ESTOQUE IS
    V_QTD NUMBER := 0;
BEGIN
    MERGE INTO DIM_ESTOQUE D
    USING (
        SELECT -1 AS COD_ESTOQUE, 'NAO INFORMADO' AS NOM_ESTOQUE FROM DUAL
        UNION ALL
        SELECT COD_ESTOQUE, NOM_ESTOQUE FROM CP_ESTOQUE
    ) S
       ON (D.COD_ESTOQUE = S.COD_ESTOQUE)
    WHEN MATCHED THEN UPDATE SET
        D.NOM_ESTOQUE = S.NOM_ESTOQUE
    WHEN NOT MATCHED THEN INSERT (
        COD_ESTOQUE,
        NOM_ESTOQUE
    ) VALUES (
        S.COD_ESTOQUE,
        S.NOM_ESTOQUE
    );

    V_QTD := SQL%ROWCOUNT;
    COMMIT;

    SP_REGISTRA_LOG_ETL('SP_CARGA_DIM_ESTOQUE', V_QTD, 'SUCESSO', 'Carga concluída com MERGE.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        SP_REGISTRA_LOG_ETL('SP_CARGA_DIM_ESTOQUE', 0, 'ERRO', SQLERRM);
        RAISE;
END;
/

PROMPT === Executando SP_CARGA_DIM_ESTOQUE ===
BEGIN
    SP_CARGA_DIM_ESTOQUE;
END;
/
