PROMPT === Procedure SP_CARGA_FATO_ESTOQUE ===

CREATE OR REPLACE PROCEDURE SP_CARGA_FATO_ESTOQUE IS
    V_QTD NUMBER := 0;
BEGIN
    INSERT INTO FATO_ESTOQUE (
        SK_TEMPO,
        SK_PRODUTO,
        SK_TIPO_MOVIMENTO,
        SK_ESTOQUE,
        SEQ_MOVIMENTO,
        QTD_MOVIMENTO,
        STA_SAIDA_ENTRADA
    )
    WITH SRC AS (
        SELECT
            ME.SEQ_MOVIMENTO_ESTOQUE AS SEQ_MOVIMENTO,
            NVL(TRUNC(ME.DAT_MOVIMENTO_ESTOQUE), DATE '1900-01-01') AS DAT_MOVIMENTO,
            NVL(ME.COD_PRODUTO, -1) AS COD_PRODUTO,
            NVL(ME.COD_TIPO_MOVIMENTO_ESTOQUE, -1) AS COD_TIPO_MOVIMENTO_ESTOQUE,
            NVL(TME.STA_SAIDA_ENTRADA, 'N') AS STA_SAIDA_ENTRADA,
            NVL(ME.QTD_MOVIMENTACAO_ESTOQUE, 0) AS QTD_MOV_BASE,
            NVL(
                (
                    SELECT MAX(EP.COD_ESTOQUE) KEEP (DENSE_RANK LAST ORDER BY EP.DAT_ESTOQUE)
                    FROM CP_ESTOQUE_PRODUTO EP
                    WHERE EP.COD_PRODUTO = ME.COD_PRODUTO
                      AND EP.DAT_ESTOQUE <= NVL(ME.DAT_MOVIMENTO_ESTOQUE, DATE '1900-01-01')
                ),
                -1
            ) AS COD_ESTOQUE
        FROM CP_MOVIMENTO_ESTOQUE ME
        LEFT JOIN CP_TIPO_MOVIMENTO_ESTOQUE TME
               ON TME.COD_TIPO_MOVIMENTO_ESTOQUE = ME.COD_TIPO_MOVIMENTO_ESTOQUE
    ),
    LKP AS (
        SELECT
            S.SEQ_MOVIMENTO,
            S.STA_SAIDA_ENTRADA,
            CASE
                WHEN S.STA_SAIDA_ENTRADA = 'S' THEN S.QTD_MOV_BASE * -1
                ELSE S.QTD_MOV_BASE
            END AS QTD_MOVIMENTO,
            DT.SK_TEMPO,
            DP.SK_PRODUTO,
            DTM.SK_TIPO_MOVIMENTO,
            DE.SK_ESTOQUE
        FROM SRC S
        LEFT JOIN DIM_TEMPO DT
               ON DT.DAT_COMPLETA = S.DAT_MOVIMENTO
        LEFT JOIN DIM_PRODUTO DP
               ON DP.COD_PRODUTO = S.COD_PRODUTO
        LEFT JOIN DIM_TIPO_MOVIMENTO DTM
               ON DTM.COD_TIPO_MOVIMENTO_ESTOQUE = S.COD_TIPO_MOVIMENTO_ESTOQUE
        LEFT JOIN DIM_ESTOQUE DE
               ON DE.COD_ESTOQUE = S.COD_ESTOQUE
    ),
    UK AS (
        SELECT
            (SELECT SK_TEMPO FROM DIM_TEMPO WHERE DAT_COMPLETA = DATE '1900-01-01') AS SK_TEMPO_UNK,
            (SELECT SK_PRODUTO FROM DIM_PRODUTO WHERE COD_PRODUTO = -1) AS SK_PRODUTO_UNK,
            (SELECT SK_TIPO_MOVIMENTO FROM DIM_TIPO_MOVIMENTO WHERE COD_TIPO_MOVIMENTO_ESTOQUE = -1) AS SK_TIPO_UNK,
            (SELECT SK_ESTOQUE FROM DIM_ESTOQUE WHERE COD_ESTOQUE = -1) AS SK_ESTOQUE_UNK
        FROM DUAL
    )
    SELECT
        NVL(L.SK_TEMPO, U.SK_TEMPO_UNK) AS SK_TEMPO,
        NVL(L.SK_PRODUTO, U.SK_PRODUTO_UNK) AS SK_PRODUTO,
        NVL(L.SK_TIPO_MOVIMENTO, U.SK_TIPO_UNK) AS SK_TIPO_MOVIMENTO,
        NVL(L.SK_ESTOQUE, U.SK_ESTOQUE_UNK) AS SK_ESTOQUE,
        L.SEQ_MOVIMENTO,
        NVL(L.QTD_MOVIMENTO, 0) AS QTD_MOVIMENTO,
        NVL(L.STA_SAIDA_ENTRADA, 'N') AS STA_SAIDA_ENTRADA
    FROM LKP L
    CROSS JOIN UK U
    WHERE NOT EXISTS (
        SELECT 1
        FROM FATO_ESTOQUE F
        WHERE F.SEQ_MOVIMENTO = L.SEQ_MOVIMENTO
    );

    V_QTD := SQL%ROWCOUNT;
    COMMIT;

    SP_REGISTRA_LOG_ETL('SP_CARGA_FATO_ESTOQUE', V_QTD, 'SUCESSO', 'Carga da fato concluída com INSERT + NOT EXISTS.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        SP_REGISTRA_LOG_ETL('SP_CARGA_FATO_ESTOQUE', 0, 'ERRO', SQLERRM);
        RAISE;
END;
/

PROMPT === Executando SP_CARGA_FATO_ESTOQUE ===
BEGIN
    SP_CARGA_FATO_ESTOQUE;
END;
/
