PROMPT === Procedure SP_ETL_ESTOQUE_COMPLETO ===

CREATE OR REPLACE PROCEDURE SP_ETL_ESTOQUE_COMPLETO IS
BEGIN
    SP_CARGA_DIM_TEMPO;
    SP_CARGA_DIM_PRODUTO;
    SP_CARGA_DIM_TIPO_MOVIMENTO;
    SP_CARGA_DIM_ESTOQUE;
    SP_CARGA_FATO_ESTOQUE;

    SP_REGISTRA_LOG_ETL('SP_ETL_ESTOQUE_COMPLETO', NULL, 'SUCESSO', 'Orquestração completa executada com sucesso.');
EXCEPTION
    WHEN OTHERS THEN
        SP_REGISTRA_LOG_ETL('SP_ETL_ESTOQUE_COMPLETO', NULL, 'ERRO', SQLERRM);
        RAISE;
END;
/

PROMPT === Executando SP_ETL_ESTOQUE_COMPLETO ===
BEGIN
    SP_ETL_ESTOQUE_COMPLETO;
END;
/
