PROMPT === Consulta A: Total de entradas e saídas por produto no último trimestre disponível ===
WITH PARAM AS (
    SELECT MAX(DT.DAT_COMPLETA) AS DATA_BASE
    FROM FATO_ESTOQUE FE
    JOIN DIM_TEMPO DT ON DT.SK_TEMPO = FE.SK_TEMPO
)
SELECT
    DP.NOM_PRODUTO,
    DTM.DES_TIPO_MOVIMENTO_ESTOQUE AS TIPO_MOVIMENTO,
    SUM(FE.QTD_MOVIMENTO) AS QTD_LIQUIDA,
    SUM(ABS(FE.QTD_MOVIMENTO)) AS QTD_ABSOLUTA
FROM FATO_ESTOQUE FE
JOIN DIM_PRODUTO DP
  ON DP.SK_PRODUTO = FE.SK_PRODUTO
JOIN DIM_TIPO_MOVIMENTO DTM
  ON DTM.SK_TIPO_MOVIMENTO = FE.SK_TIPO_MOVIMENTO
JOIN DIM_TEMPO DT
  ON DT.SK_TEMPO = FE.SK_TEMPO
CROSS JOIN PARAM P
WHERE DT.DAT_COMPLETA >= ADD_MONTHS(TRUNC(P.DATA_BASE, 'Q'), -3)
  AND DT.DAT_COMPLETA < TRUNC(P.DATA_BASE, 'Q')
GROUP BY DP.NOM_PRODUTO, DTM.DES_TIPO_MOVIMENTO_ESTOQUE
ORDER BY DP.NOM_PRODUTO, TIPO_MOVIMENTO;

PROMPT === Consulta B: Saldo atual de cada produto por depósito ===
SELECT
    DP.NOM_PRODUTO,
    DE.NOM_ESTOQUE,
    SUM(FE.QTD_MOVIMENTO) AS SALDO_ATUAL
FROM FATO_ESTOQUE FE
JOIN DIM_PRODUTO DP
  ON DP.SK_PRODUTO = FE.SK_PRODUTO
JOIN DIM_ESTOQUE DE
  ON DE.SK_ESTOQUE = FE.SK_ESTOQUE
GROUP BY DP.NOM_PRODUTO, DE.NOM_ESTOQUE
ORDER BY DP.NOM_PRODUTO, DE.NOM_ESTOQUE;

PROMPT === Consulta C: Top 5 produtos com maior volume de saída no mês disponível mais recente ===
WITH PARAM AS (
    SELECT MAX(DT.DAT_COMPLETA) AS DATA_BASE
    FROM FATO_ESTOQUE FE
    JOIN DIM_TEMPO DT ON DT.SK_TEMPO = FE.SK_TEMPO
)
SELECT
    DP.NOM_PRODUTO,
    ABS(SUM(FE.QTD_MOVIMENTO)) AS TOTAL_SAIDA
FROM FATO_ESTOQUE FE
JOIN DIM_PRODUTO DP
  ON DP.SK_PRODUTO = FE.SK_PRODUTO
JOIN DIM_TIPO_MOVIMENTO DTM
  ON DTM.SK_TIPO_MOVIMENTO = FE.SK_TIPO_MOVIMENTO
JOIN DIM_TEMPO DT
  ON DT.SK_TEMPO = FE.SK_TEMPO
CROSS JOIN PARAM P
WHERE DTM.STA_SAIDA_ENTRADA = 'S'
  AND DT.NUM_ANO = EXTRACT(YEAR FROM P.DATA_BASE)
  AND DT.NUM_MES = EXTRACT(MONTH FROM P.DATA_BASE)
GROUP BY DP.NOM_PRODUTO
ORDER BY TOTAL_SAIDA DESC
FETCH FIRST 5 ROWS ONLY;

PROMPT === Consulta D: Comparativo mensal de entradas vs saídas (últimos 6 meses disponíveis) ===
WITH PARAM AS (
    SELECT MAX(DT.DAT_COMPLETA) AS DATA_BASE
    FROM FATO_ESTOQUE FE
    JOIN DIM_TEMPO DT ON DT.SK_TEMPO = FE.SK_TEMPO
),
BASE AS (
    SELECT
        CASE
            WHEN DTM.STA_SAIDA_ENTRADA = 'E' THEN 'ENTRADA'
            WHEN DTM.STA_SAIDA_ENTRADA = 'S' THEN 'SAIDA'
            ELSE 'OUTROS'
        END AS TIPO,
        TO_CHAR(DT.DAT_COMPLETA, 'YYYY-MM') AS MES_REFERENCIA,
        ABS(FE.QTD_MOVIMENTO) AS QTD_MOVIMENTO,
        P.DATA_BASE
    FROM FATO_ESTOQUE FE
    JOIN DIM_TIPO_MOVIMENTO DTM
      ON DTM.SK_TIPO_MOVIMENTO = FE.SK_TIPO_MOVIMENTO
    JOIN DIM_TEMPO DT
      ON DT.SK_TEMPO = FE.SK_TEMPO
    CROSS JOIN PARAM P
    WHERE DT.DAT_COMPLETA >= ADD_MONTHS(TRUNC(P.DATA_BASE, 'MM'), -5)
)
SELECT
    TIPO,
    SUM(CASE WHEN MES_REFERENCIA = TO_CHAR(ADD_MONTHS(TRUNC(DATA_BASE, 'MM'), -5), 'YYYY-MM') THEN QTD_MOVIMENTO ELSE 0 END) AS MES_M5,
    SUM(CASE WHEN MES_REFERENCIA = TO_CHAR(ADD_MONTHS(TRUNC(DATA_BASE, 'MM'), -4), 'YYYY-MM') THEN QTD_MOVIMENTO ELSE 0 END) AS MES_M4,
    SUM(CASE WHEN MES_REFERENCIA = TO_CHAR(ADD_MONTHS(TRUNC(DATA_BASE, 'MM'), -3), 'YYYY-MM') THEN QTD_MOVIMENTO ELSE 0 END) AS MES_M3,
    SUM(CASE WHEN MES_REFERENCIA = TO_CHAR(ADD_MONTHS(TRUNC(DATA_BASE, 'MM'), -2), 'YYYY-MM') THEN QTD_MOVIMENTO ELSE 0 END) AS MES_M2,
    SUM(CASE WHEN MES_REFERENCIA = TO_CHAR(ADD_MONTHS(TRUNC(DATA_BASE, 'MM'), -1), 'YYYY-MM') THEN QTD_MOVIMENTO ELSE 0 END) AS MES_M1,
    SUM(CASE WHEN MES_REFERENCIA = TO_CHAR(TRUNC(DATA_BASE, 'MM'), 'YYYY-MM') THEN QTD_MOVIMENTO ELSE 0 END) AS MES_ATUAL
FROM BASE
GROUP BY TIPO
ORDER BY TIPO;

PROMPT === Consulta E: Produto com maior variação de estoque entre o mês disponível atual e o anterior ===
WITH PARAM AS (
    SELECT MAX(DT.DAT_COMPLETA) AS DATA_BASE
    FROM FATO_ESTOQUE FE
    JOIN DIM_TEMPO DT ON DT.SK_TEMPO = FE.SK_TEMPO
),
MOV_MENSAL AS (
    SELECT
        DP.NOM_PRODUTO,
        TRUNC(DT.DAT_COMPLETA, 'MM') AS MES_REF,
        SUM(FE.QTD_MOVIMENTO) AS SALDO_MES,
        P.DATA_BASE
    FROM FATO_ESTOQUE FE
    JOIN DIM_PRODUTO DP
      ON DP.SK_PRODUTO = FE.SK_PRODUTO
    JOIN DIM_TEMPO DT
      ON DT.SK_TEMPO = FE.SK_TEMPO
    CROSS JOIN PARAM P
    WHERE TRUNC(DT.DAT_COMPLETA, 'MM') IN (
        ADD_MONTHS(TRUNC(P.DATA_BASE, 'MM'), -1),
        TRUNC(P.DATA_BASE, 'MM')
    )
    GROUP BY DP.NOM_PRODUTO, TRUNC(DT.DAT_COMPLETA, 'MM'), P.DATA_BASE
),
COMPARA AS (
    SELECT
        NOM_PRODUTO,
        SUM(CASE WHEN MES_REF = TRUNC(DATA_BASE, 'MM') THEN SALDO_MES ELSE 0 END) AS SALDO_MES_ATUAL,
        SUM(CASE WHEN MES_REF = ADD_MONTHS(TRUNC(DATA_BASE, 'MM'), -1) THEN SALDO_MES ELSE 0 END) AS SALDO_MES_ANTERIOR
    FROM MOV_MENSAL
    GROUP BY NOM_PRODUTO
)
SELECT
    NOM_PRODUTO,
    SALDO_MES_ANTERIOR,
    SALDO_MES_ATUAL,
    (SALDO_MES_ATUAL - SALDO_MES_ANTERIOR) AS VARIACAO
FROM COMPARA
ORDER BY ABS(SALDO_MES_ATUAL - SALDO_MES_ANTERIOR) DESC
FETCH FIRST 1 ROWS ONLY;
