PROMPT === Validação rápida da origem e do DW ===

SELECT 'CP_PRODUTO' AS TABELA, COUNT(*) AS QTD FROM CP_PRODUTO
UNION ALL SELECT 'CP_ESTOQUE', COUNT(*) FROM CP_ESTOQUE
UNION ALL SELECT 'CP_TIPO_MOVIMENTO_ESTOQUE', COUNT(*) FROM CP_TIPO_MOVIMENTO_ESTOQUE
UNION ALL SELECT 'CP_ESTOQUE_PRODUTO', COUNT(*) FROM CP_ESTOQUE_PRODUTO
UNION ALL SELECT 'CP_MOVIMENTO_ESTOQUE', COUNT(*) FROM CP_MOVIMENTO_ESTOQUE
UNION ALL SELECT 'DIM_TEMPO', COUNT(*) FROM DIM_TEMPO
UNION ALL SELECT 'DIM_PRODUTO', COUNT(*) FROM DIM_PRODUTO
UNION ALL SELECT 'DIM_TIPO_MOVIMENTO', COUNT(*) FROM DIM_TIPO_MOVIMENTO
UNION ALL SELECT 'DIM_ESTOQUE', COUNT(*) FROM DIM_ESTOQUE
UNION ALL SELECT 'FATO_ESTOQUE', COUNT(*) FROM FATO_ESTOQUE;
